name: Application CI
on: [push, pull_request]
jobs:
    pipeline:
        name: gateway pipeline
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
        timeout-minutes: 40
        env:
            NODE_VERSION: 14.15.0
            SPRING_OUTPUT_ANSI_ENABLED: DETECT
            SPRING_JPA_SHOW_SQL: false
            JHI_DISABLE_WEBPACK_LOGS: true
            NG_CLI_ANALYTICS: false
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14.15.0
            - uses: actions/setup-java@v1
              with:
                  java-version: '11.x'
            - name: Install node.js packages
              run: yarn install
            - name: Build blog
              run: |
                cd blog
                yarn run java:docker
            - name: Build gateway
              run: |
                cd gateway
                yarn run java:docker
            - name: Start docker
              run: docker-compose -f docker-compose/docker-compose.yml up -d
            - name: 'E2E: Run'
              run: yarn run ci:e2e:run
            - name: 'E2E: Teardown'
              run: yarn run ci:e2e:teardown
